# Generated by Django 2.2.9 on 2020-01-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='profil_picture',
            new_name='profile_picture',
        ),
    ]
