# Generated by Django 2.2.10 on 2020-02-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_myuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
