# Generated by Django 2.2.10 on 2020-02-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
