# Generated by Django 2.2.10 on 2020-02-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_number_verification',
            field=models.BooleanField(default=False),
        ),
    ]
