# Generated by Django 2.2.11 on 2020-03-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200319_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
