# Generated by Django 2.2.11 on 2020-03-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200319_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='city_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='continent_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='country_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
