# Generated by Django 2.2.11 on 2020-03-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200319_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='facebook_admin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
