# Generated by Django 2.2.11 on 2020-03-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_myuser_facebook_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='facebook_admin',
            new_name='facebook_id',
        ),
    ]
