# Generated by Django 2.2.11 on 2020-04-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200324_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
