# Generated by Django 2.2.12 on 2020-04-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0015_socialconnection'),
        ('account', '0015_myuser_profile_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='facebook_id',
        ),
        migrations.AddField(
            model_name='myuser',
            name='social_connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_network.SocialConnection'),
        ),
    ]
