# Generated by Django 2.2.12 on 2020-04-30 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20200430_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='city_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='continent_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='country_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='device_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='postal_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
