# Generated by Django 2.2.12 on 2020-06-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200610_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
