# Generated by Django 2.2.12 on 2020-06-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20200610_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='latitude',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='connection',
            name='longitude',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
