# Generated by Django 2.2.12 on 2020-06-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20200610_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='connection',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
    ]
