# Generated by Django 2.2.13 on 2020-07-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20200702_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='settings_wall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Wall'),
        ),
    ]
