# Generated by Django 2.2.13 on 2020-07-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20200702_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='id_page_facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
