# Generated by Django 2.2.13 on 2020-07-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20200702_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='instagram_business',
            field=models.BooleanField(default=False),
        ),
    ]
