# Generated by Django 2.2.13 on 2020-07-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_wall_instagram_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall',
            name='instagram_business',
        ),
    ]
