# Generated by Django 2.2.9 on 2020-01-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='number',
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
