# Generated by Django 2.2.9 on 2020-01-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_coupon_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
