# Generated by Django 2.2.10 on 2020-02-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_coupon_distributed'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='type_of_distribution',
            field=models.CharField(choices=[('direct', 'DIRECT'), ('end_promotion', 'END_PROMOTION'), ('live_draw', 'LIVE_DRAW')], default='direct', max_length=10),
        ),
    ]
