# Generated by Django 2.2.12 on 2020-05-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0009_coupon_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type_of_distribution',
            field=models.CharField(choices=[('raffle', 'RAFFLE'), ('giveaway', 'GIVEAWAY'), ('reward', 'REWARD')], default='direct', max_length=20),
        ),
    ]
