# Generated by Django 2.2.12 on 2020-05-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0010_auto_20200519_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='expiration_date',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type_of_distribution',
            field=models.CharField(choices=[('raffle', 'RAFFLE'), ('giveaway', 'GIVEAWAY'), ('reward', 'REWARD')], max_length=20),
        ),
    ]
