# Generated by Django 2.2.12 on 2020-05-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0011_auto_20200519_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='number',
        ),
    ]
