# Generated by Django 2.2.10 on 2020-03-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_comment', models.BooleanField(default=False)),
                ('facebook_follow', models.BooleanField(default=False)),
                ('facebook_like', models.BooleanField(default=False)),
                ('youtube_like', models.BooleanField(default=False)),
                ('youtube_follow', models.BooleanField(default=False)),
                ('instagram_follow', models.BooleanField(default=False)),
                ('instagram_like', models.BooleanField(default=False)),
                ('instagram_comment', models.BooleanField(default=False)),
                ('twitter_like', models.BooleanField(default=False)),
                ('twitter_comment', models.BooleanField(default=False)),
                ('twitter_retweet', models.BooleanField(default=False)),
                ('twicth_comment', models.BooleanField(default=False)),
                ('twitch_follow', models.BooleanField(default=False)),
                ('twitch_like', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Socials Actions',
                'verbose_name': 'Social Action',
            },
        ),
    ]
