# Generated by Django 2.2.10 on 2020-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_auto_20200302_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaction',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
