# Generated by Django 2.2.10 on 2020-03-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_socialaction_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaction',
            name='url_video',
            field=models.URLField(default=None),
        ),
    ]
