# Generated by Django 2.2.11 on 2020-03-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_auto_20200320_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaction',
            name='url_video',
        ),
    ]
