# Generated by Django 2.2.11 on 2020-03-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0007_remove_socialaction_url_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaction',
            name='url_video',
            field=models.URLField(default=None, null=True),
        ),
    ]
