# Generated by Django 2.2.11 on 2020-03-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0008_socialaction_url_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaction',
            name='video_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
