# Generated by Django 2.2.11 on 2020-04-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0009_socialaction_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaction',
            name='video',
            field=models.BooleanField(default=False),
        ),
    ]
