# Generated by Django 2.2.11 on 2020-04-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0010_socialaction_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaction',
            name='url_video',
        ),
        migrations.RemoveField(
            model_name='socialaction',
            name='video_name',
        ),
    ]

