# Generated by Django 2.2.11 on 2020-04-02 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0023_auto_20200402_0809'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_network', '0011_auto_20200402_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_comment', models.BooleanField(default=False)),
                ('facebook_follow', models.BooleanField(default=False)),
                ('facebook_like', models.BooleanField(default=False)),
                ('youtube_like', models.BooleanField(default=False)),
                ('youtube_follow', models.BooleanField(default=False)),
                ('instagram_follow', models.BooleanField(default=False)),
                ('instagram_like', models.BooleanField(default=False)),
                ('instagram_comment', models.BooleanField(default=False)),
                ('twitter_like', models.BooleanField(default=False)),
                ('twitter_comment', models.BooleanField(default=False)),
                ('twitter_retweet', models.BooleanField(default=False)),
                ('twitter_follow', models.BooleanField(default=False)),
                ('twicth_comment', models.BooleanField(default=False)),
                ('twitch_follow', models.BooleanField(default=False)),
                ('twitch_like', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('video', models.BooleanField(default=False)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.Promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User social action',
                'verbose_name_plural': 'User socials actions',
            },
        ),
    ]

