# Generated by Django 2.2.11 on 2020-04-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0012_usersocialaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialaction',
            old_name='pool',
            new_name='poll',
        ),
        migrations.RenameField(
            model_name='socialaction',
            old_name='twicth_comment',
            new_name='twitch_comment',
        ),
        migrations.RenameField(
            model_name='usersocialaction',
            old_name='pool',
            new_name='poll',
        ),
        migrations.RenameField(
            model_name='usersocialaction',
            old_name='twicth_comment',
            new_name='twitch_comment',
        ),
    ]
