# Generated by Django 2.2.12 on 2020-04-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0015_socialconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='twitter_oauth_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='twitter_oauth_token_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
