# Generated by Django 2.2.12 on 2020-04-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0016_auto_20200416_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='twitter_access_token_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
