# Generated by Django 2.2.12 on 2020-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0017_socialconnection_twitter_access_token_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='twitter_connected',
            field=models.BooleanField(default=False),
        ),
    ]
