# Generated by Django 2.2.12 on 2020-04-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0018_socialconnection_twitter_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
