# Generated by Django 2.2.12 on 2020-04-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0019_socialconnection_twitter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialconnection',
            old_name='twitter_access_token_data',
            new_name='twitter_connection_oauth_token',
        ),
        migrations.RenameField(
            model_name='socialconnection',
            old_name='twitter_oauth_token',
            new_name='twitter_connection_oauth_token_secret',
        ),
        migrations.RemoveField(
            model_name='socialconnection',
            name='twitter_connected',
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='twitter_oauth_token_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
