# Generated by Django 2.2.12 on 2020-04-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0020_auto_20200417_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='twitter_connected',
            field=models.BooleanField(default=False),
        ),
    ]
