# Generated by Django 2.2.12 on 2020-04-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0021_socialconnection_twitter_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaction',
            name='twitter_comment_model',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
