# Generated by Django 2.2.12 on 2020-04-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0022_socialaction_twitter_comment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaction',
            name='twitter_retweet_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
