# Generated by Django 2.2.12 on 2020-04-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0023_socialaction_twitter_retweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaction',
            name='twitter_like_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
