# Generated by Django 2.2.12 on 2020-04-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0024_socialaction_twitter_like_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaction',
            name='twitter_follow_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialaction',
            name='twitter_follow_type',
            field=models.CharField(choices=[('user_id', 'USER_ID'), ('screen_name', 'SCREEN_NAME')], max_length=10, null=True),
        ),
    ]
