# Generated by Django 2.2.12 on 2020-04-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0025_auto_20200421_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaction',
            name='twitter_follow_type',
            field=models.CharField(choices=[('user_id', 'USER_ID'), ('screen_name', 'SCREEN_NAME')], max_length=15, null=True),
        ),
    ]
