# Generated by Django 2.2.12 on 2020-04-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0026_auto_20200421_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
