# Generated by Django 2.2.12 on 2020-04-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0030_auto_20200427_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialconnection',
            name='google_id_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='socialconnection',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='socialconnection',
            name='google_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
