# Generated by Django 2.2.12 on 2020-04-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0033_auto_20200427_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaction',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
