# Generated by Django 2.2.12 on 2020-04-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0034_socialaction_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaction',
            name='website',
            field=models.BooleanField(default=False),
        ),
    ]
