# Generated by Django 2.2.12 on 2020-05-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0037_usersocialaction_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='twitch_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='twitch_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='twitch_refresh_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='twitch_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
