# Generated by Django 2.2.12 on 2020-05-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0038_auto_20200509_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialconnection',
            name='twitch_id',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
