# Generated by Django 2.2.12 on 2020-05-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0039_auto_20200509_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='twitch_channel_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='twitch_channel_url',
            field=models.URLField(null=True),
        ),
    ]
