# Generated by Django 2.2.12 on 2020-05-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0041_auto_20200511_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='twitch_id_token',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='socialconnection',
            name='twitch_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
