# Generated by Django 2.2.12 on 2020-05-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0042_auto_20200511_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialconnection',
            old_name='twitch_id',
            new_name='twitch_client_id',
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='twitch_user_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
