# Generated by Django 2.2.12 on 2020-05-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0043_auto_20200511_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaction',
            name='twitch_comment',
        ),
        migrations.RemoveField(
            model_name='socialaction',
            name='twitch_like',
        ),
        migrations.RemoveField(
            model_name='usersocialaction',
            name='twitch_comment',
        ),
        migrations.RemoveField(
            model_name='usersocialaction',
            name='twitch_like',
        ),
    ]
