# Generated by Django 2.2.12 on 2020-05-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0044_auto_20200511_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaction',
            name='twitch_follow_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
