# Generated by Django 2.2.12 on 2020-05-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0045_socialaction_twitch_follow_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialaction',
            old_name='instagram_comment',
            new_name='instagram_profile_url',
        ),
        migrations.RenameField(
            model_name='usersocialaction',
            old_name='instagram_follow',
            new_name='instagram_publication_url',
        ),
        migrations.RemoveField(
            model_name='socialaction',
            name='instagram_comment',
        ),
        migrations.RemoveField(
            model_name='socialaction',
            name='instagram_follow',
        ),
        migrations.RemoveField(
            model_name='socialaction',
            name='instagram_like',
        ),
        migrations.RemoveField(
            model_name='usersocialaction',
            name='instagram_like',
        ),
        migrations.AddField(
            model_name='socialaction',
            name='instagram_profile_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='socialaction',
            name='instagram_publication_url',
            field=models.URLField(null=True),
        ),
    ]
