# Generated by Django 2.2.12 on 2020-05-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0046_auto_20200511_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialaction',
            old_name='instagram_profile_url',
            new_name='instagram_profile',
        ),
        migrations.RenameField(
            model_name='usersocialaction',
            old_name='instagram_publication_url',
            new_name='instagram_publication',
        ),
        migrations.AddField(
            model_name='socialaction',
            name='instagram_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialaction',
            name='instagram_publication',
            field=models.BooleanField(default=False),
        ),
    ]
