# Generated by Django 2.2.12 on 2020-05-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0048_socialconnection_twitch_connected_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaction',
            name='video_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='socialaction',
            name='website_url',
            field=models.URLField(null=True),
        ),
    ]
