# Generated by Django 2.2.12 on 2020-05-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0049_auto_20200519_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_entries', models.IntegerField(default=1)),
                ('website_mandatory', models.BooleanField(default=False)),
                ('video_entries', models.IntegerField(default=1)),
                ('video_mandatory', models.BooleanField(default=False)),
                ('pool_entries', models.IntegerField(default=1)),
                ('pool_mandatory', models.BooleanField(default=False)),
                ('facebook_comment_entries', models.IntegerField(default=1)),
                ('facebook_comment_mandatory', models.BooleanField(default=False)),
                ('facebook_follow_entries', models.IntegerField(default=1)),
                ('facebook_follow_mandatory', models.BooleanField(default=False)),
                ('facebook_like_entries', models.IntegerField(default=1)),
                ('facebook_like_mandatory', models.BooleanField(default=False)),
                ('youtube_like_entries', models.IntegerField(default=1)),
                ('youtube_like_mandatory', models.BooleanField(default=False)),
                ('youtube_follow_entries', models.IntegerField(default=1)),
                ('youtube_follow_mandatory', models.BooleanField(default=False)),
                ('instagram_profile_entries', models.IntegerField(default=1)),
                ('instagram_profile_mandatory', models.BooleanField(default=False)),
                ('instagram_publication_entries', models.IntegerField(default=1)),
                ('instagram_publication_mandatory', models.BooleanField(default=False)),
                ('twitter_like_entries', models.IntegerField(default=1)),
                ('twitter_like_mandatory', models.BooleanField(default=False)),
                ('twitter_follow_entries', models.IntegerField(default=1)),
                ('twitter_follow_mandatory', models.BooleanField(default=False)),
                ('twitter_retweet_entries', models.IntegerField(default=1)),
                ('twitter_retweet_mandatory', models.BooleanField(default=False)),
                ('twitter_tweet_entries', models.IntegerField(default=1)),
                ('tweeter_tweet_mandatory', models.BooleanField(default=False)),
                ('twitch_follow_entries', models.IntegerField(default=1)),
                ('twitch_follow_mandatory', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='socialaction',
            name='entries',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Entries', to='social_network.Entries'),
        ),
    ]
