# Generated by Django 2.2.12 on 2020-05-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0050_auto_20200519_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='tweeter_tweet_mandatory',
            new_name='twitter_tweet_mandatory',
        ),
    ]
