# Generated by Django 2.2.12 on 2020-05-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0052_auto_20200522_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaction',
            name='instagram_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialaction',
            name='instagram_publication_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialaction',
            name='twitch_follow_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialaction',
            name='twitter_follow_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialaction',
            name='twitter_follow_type',
            field=models.CharField(blank=True, choices=[('user_id', 'USER_ID'), ('screen_name', 'SCREEN_NAME')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='socialaction',
            name='twitter_like_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialaction',
            name='twitter_retweet_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialaction',
            name='twitter_tweet_model',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
