# Generated by Django 2.2.12 on 2020-05-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0053_auto_20200526_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialaction',
            name='entries',
            field=models.IntegerField(default=0),
        ),
    ]
