# Generated by Django 2.2.12 on 2020-05-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0054_usersocialaction_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialaction',
            name='distributed',
            field=models.BooleanField(default=False),
        ),
    ]
