# Generated by Django 2.2.12 on 2020-05-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0055_usersocialaction_distributed'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaction',
            name='video_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialaction',
            name='video_url_mobile',
            field=models.URLField(null=True),
        ),
    ]
