# Generated by Django 2.2.12 on 2020-06-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0056_auto_20200527_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaction',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialaction',
            name='video_url_mobile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialaction',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
