# Generated by Django 2.2.12 on 2020-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0060_auto_20200612_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialconnection',
            name='snapchat_refresh_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='socialconnection',
            name='snapchat_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
