# Generated by Django 2.2.13 on 2020-06-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0061_auto_20200612_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='instagram_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='instagram_date_token',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='instagram_long_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='instagram_short_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
