# Generated by Django 2.2.13 on 2020-06-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0063_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='twitter_access_token',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
