# Generated by Django 2.2.13 on 2020-06-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0064_auto_20200625_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='facebook_long_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='facebook_short_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
