# Generated by Django 2.2.13 on 2020-06-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0065_auto_20200629_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialconnection',
            old_name='facebook_connected',
            new_name='facebook_login_connected',
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='facebook_rights_connected',
            field=models.BooleanField(default=False),
        ),
    ]
