# Generated by Django 2.2.13 on 2020-06-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0066_auto_20200629_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='facebook_date_token',
            field=models.DateField(blank=True, null=True),
        ),
    ]
