# Generated by Django 2.2.13 on 2020-07-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0067_socialconnection_facebook_date_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='facebook_post_entries',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='entries',
            name='facebook_post_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialaction',
            name='facebook_comment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaction',
            name='facebook_comment_model',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='socialaction',
            name='facebook_like_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaction',
            name='facebook_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialaction',
            name='facebook_post_model',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usersocialaction',
            name='facebook_post',
            field=models.BooleanField(default=False),
        ),
    ]
