# Generated by Django 2.2.13 on 2020-07-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0068_auto_20200701_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='facebook_page_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
