# Generated by Django 2.2.13 on 2020-07-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0069_socialconnection_facebook_page_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='facebook_page_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
