# Generated by Django 2.2.13 on 2020-07-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0070_socialconnection_facebook_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='instagram_business_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='instagram_business_date_token',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='instagram_business_long_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='instagram_business_short_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
