# Generated by Django 2.2.13 on 2020-07-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0072_socialconnection_instagram_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
