# Generated by Django 2.2.13 on 2020-07-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0073_socialconnection_instagram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='facebook_page_connected',
            field=models.BooleanField(default=False),
        ),
    ]
