# Generated by Django 2.2.13 on 2020-07-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0075_auto_20200721_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialaction',
            old_name='facebook_comment',
            new_name='facebook_page',
        ),
        migrations.RenameField(
            model_name='usersocialaction',
            old_name='facebook_follow',
            new_name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='usersocialaction',
            name='facebook_like',
        ),
    ]
