# Generated by Django 2.2.12 on 2020-05-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnumbers',
            name='rafflee_followers',
            field=models.IntegerField(default=0),
        ),
    ]
