# Generated by Django 2.2.12 on 2020-05-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0041_auto_20200527_1753'),
        ('analytics', '0002_socialnumbers_rafflee_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_views', models.IntegerField(default=0)),
                ('click_actions', models.IntegerField(default=0)),
                ('click_participations', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.Promotion')),
            ],
            options={
                'verbose_name': 'Promotion number',
                'verbose_name_plural': 'Promotion numbers',
            },
        ),
    ]
