# Generated by Django 2.2.12 on 2020-06-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_promotionnumbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionnumbers',
            name='product_benefit_by_action',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotionnumbers',
            name='product_benefit_by_participations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotionnumbers',
            name='product_benefit_by_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotionnumbers',
            name='product_benefit_by_view',
            field=models.IntegerField(default=0),
        ),
    ]
