# Generated by Django 2.2.12 on 2020-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20200602_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionnumbers',
            name='click_actions_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotionnumbers',
            name='click_participations_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotionnumbers',
            name='click_views_total',
            field=models.IntegerField(default=0),
        ),
    ]
