# Generated by Django 2.2.12 on 2020-06-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20200605_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionnumbers',
            name='product_benefit_by_action',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='promotionnumbers',
            name='product_benefit_by_participations',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='promotionnumbers',
            name='product_benefit_by_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='promotionnumbers',
            name='product_benefit_by_view',
            field=models.FloatField(default=0),
        ),
    ]
