# Generated by Django 2.2.13 on 2020-07-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20200605_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionnumbers',
            name='followers_benefit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='promotionnumbers',
            name='number_of_followers',
            field=models.IntegerField(default=0),
        ),
    ]
