# Generated by Django 2.2.13 on 2020-07-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20200717_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotionnumbers',
            old_name='followers_benefit',
            new_name='product_benefit_followers',
        ),
    ]
