# Generated by Django 2.2.12 on 2020-06-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=500)),
                ('type', models.CharField(choices=[('bug', 'BUG'), ('feedback', 'FEEDBACK')], default='bug', max_length=8)),
                ('description', models.TextField(blank=True, max_length=4000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('issue', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Reports',
                'verbose_name': 'Report',
            },
        ),
    ]
