# Generated by Django 2.2.10 on 2020-02-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='priority',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], unique=True),
        ),
    ]
