# Generated by Django 2.2.8 on 2019-12-14 17:58

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=50)),
                ('number_of_eligible_people', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=2048)),
                ('physical_promotion', models.BooleanField(default=False)),
                ('trade_chain', models.BooleanField(blank=True, null=True)),
                ('street_number', models.IntegerField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=2048, null=True)),
                ('city', models.CharField(blank=True, max_length=2048, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.Company')),
            ],
            options={
                'verbose_name_plural': 'Promotion',
                'verbose_name': 'Promotion',
            },
        ),
    ]
