# Generated by Django 2.2.8 on 2019-12-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='type_of_promotion',
            field=models.CharField(choices=[('private', 'PRIVATE'), ('public', 'PUBLIC')], default='public', max_length=10),
        ),
    ]
