# Generated by Django 2.2.10 on 2020-02-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0008_auto_20200228_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='result_poll',
            field=models.ManyToManyField(to='promotion.Response'),
        ),
    ]
