# Generated by Django 2.2.10 on 2020-02-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0010_response_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='responsetemplate',
            name='selected',
        ),
    ]
