# Generated by Django 2.2.10 on 2020-02-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0011_auto_20200228_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='responsetemplate',
            name='response',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
