# Generated by Django 2.2.10 on 2020-03-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0012_auto_20200228_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='responsetemplate',
            name='response',
            field=models.CharField(max_length=200),
        ),
    ]
