# Generated by Django 2.2.10 on 2020-03-02 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_socialaction'),
        ('promotion', '0013_auto_20200302_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='social_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_network.SocialAction'),
        ),
    ]
