# Generated by Django 2.2.10 on 2020-03-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0014_promotion_social_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='campaign_image',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
