# Generated by Django 2.2.10 on 2020-03-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0017_auto_20200303_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
