# Generated by Django 2.2.10 on 2020-03-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0019_auto_20200303_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winnings',
            old_name='winnings_name',
            new_name='name',
        ),
    ]
