# Generated by Django 2.2.11 on 2020-04-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0024_auto_20200407_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='winning'),
        ),
        migrations.AddField(
            model_name='winnings',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
