# Generated by Django 2.2.12 on 2020-04-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0025_auto_20200408_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='url_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
