# Generated by Django 2.2.12 on 2020-04-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0027_auto_20200430_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnings',
            name='image',
            field=models.ImageField(null=True, upload_to='winning'),
        ),
        migrations.AlterField(
            model_name='winnings',
            name='image_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
