# Generated by Django 2.2.12 on 2020-05-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0028_auto_20200430_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='close_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
