# Generated by Django 2.2.12 on 2020-05-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0030_auto_20200519_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entries',
        ),
    ]
