# Generated by Django 2.2.12 on 2020-05-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0031_delete_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
