# Generated by Django 2.2.12 on 2020-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0032_auto_20200519_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='live_draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='number_of_eligible_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
