# Generated by Django 2.2.12 on 2020-05-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0034_promotion_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='campaign_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='campaign_image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='close_promotion',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='live_draw',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotion.Poll'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='social_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_network.SocialAction'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='url_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotion.Video'),
        ),
    ]
