# Generated by Django 2.2.12 on 2020-05-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0035_auto_20200520_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='result_poll',
            field=models.ManyToManyField(blank=True, to='promotion.Response'),
        ),
    ]
