# Generated by Django 2.2.12 on 2020-05-25 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0037_auto_20200525_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='promotion.Category'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
