# Generated by Django 2.2.12 on 2020-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0038_auto_20200525_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='number_of_maximum_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
