# Generated by Django 2.2.12 on 2020-05-26 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0039_promotion_number_of_maximum_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, to='promotion.Category'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
