# Generated by Django 2.2.12 on 2020-05-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0040_auto_20200526_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url_mobile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
