# Generated by Django 2.2.12 on 2020-06-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0042_promotion_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='long_description',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
