# Generated by Django 2.2.9 on 2020-01-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_id_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id_company',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
