# Generated by Django 2.2.10 on 2020-02-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill',
            field=models.FileField(upload_to='bill'),
        ),
    ]
