# Generated by Django 2.2.11 on 2020-04-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
