# Generated by Django 2.2.11 on 2020-04-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_company_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='certified',
            field=models.BooleanField(default=False),
        ),
    ]
