# Generated by Django 2.2.12 on 2020-04-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_certified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=2064, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=2064, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id_company',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(max_length=2064, null=True),
        ),
    ]
