# Generated by Django 2.2.13 on 2020-07-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20200430_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.BooleanField(default=False)),
                ('twitter', models.BooleanField(default=False)),
                ('instagram', models.BooleanField(default=False)),
                ('id_page_facebook', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='settings_wall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Wall'),
        ),
    ]
